import { jsPDF } from "jspdf";
import type { DailyLog, DutyStatus, StopKind, TripPlan } from "./tripTypes";

// Report is drawn as vectors (crisp at any zoom, small file). Layout is in
// points; US Letter portrait = 612 x 792.
const PAGE_W = 612;
const PAGE_H = 792;
const M = 44; // page margin
const CONTENT_W = PAGE_W - M * 2;

// Brand-ish palette (kept literal so the PDF is theme-independent).
const INK = "#1a1d23";
const MUTED = "#565b66";
const FAINT = "#c9c6c0";
const LINE = "#e6e2db";
const ACCENT = "#d97528";
const DUTY: Record<DutyStatus, string> = {
  off_duty: "#8a94a6",
  sleeper: "#3b6fe0",
  driving: "#1f9d6b",
  on_duty: "#d97528",
};
const STOP_COLOR: Record<StopKind, string> = {
  start: "#8a94a6",
  current: "#8a94a6",
  pickup: "#1f9d6b",
  dropoff: "#d97528",
  fuel: "#c98a1a",
  break: "#3b6fe0",
  rest: "#7c5cd6",
};

const rowOrder: DutyStatus[] = ["off_duty", "sleeper", "driving", "on_duty"];
const rowLabels: Record<DutyStatus, string> = {
  off_duty: "Off Duty",
  sleeper: "Sleeper",
  driving: "Driving",
  on_duty: "On Duty",
};

function fmtDate(iso: string) {
  return new Date(iso + "T12:00:00").toLocaleDateString("en-US", {
    weekday: "long",
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}
function fmtHour(h: number) {
  const total = Math.round(h * 60);
  const hh = Math.floor(total / 60) % 24;
  const mm = total % 60;
  const period = hh >= 12 ? "PM" : "AM";
  const h12 = hh % 12 === 0 ? 12 : hh % 12;
  return `${h12}:${mm.toString().padStart(2, "0")} ${period}`;
}

/** Draw the running header/footer chrome on the current page. */
function chrome(doc: jsPDF, subtitle: string, page: number, total: number) {
  doc.setDrawColor(LINE);
  doc.setLineWidth(0.8);
  // top rule
  doc.line(M, M + 20, PAGE_W - M, M + 20);
  // wordmark
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(INK);
  doc.text("Spotter ELD", M, M + 12);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(MUTED);
  doc.text(subtitle, PAGE_W - M, M + 12, { align: "right" });
  // footer
  doc.setDrawColor(LINE);
  doc.line(M, PAGE_H - M, PAGE_W - M, PAGE_H - M);
  doc.setFontSize(7.5);
  doc.setTextColor(MUTED);
  doc.text("Generated by Spotter ELD · FMCSA 70h/8-day property carrier", M, PAGE_H - M + 12);
  doc.text(`Page ${page} / ${total}`, PAGE_W - M, PAGE_H - M + 12, { align: "right" });
}

function eyebrow(doc: jsPDF, text: string, x: number, y: number) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.setTextColor(MUTED);
  doc.text(text.toUpperCase(), x, y, { charSpace: 0.6 });
}

/** A vector sketch of the route with stop dots — no external map/key needed. */
function drawRouteSketch(doc: jsPDF, trip: TripPlan, x: number, y: number, w: number, h: number) {
  // Card
  doc.setFillColor("#faf9f7");
  doc.setDrawColor(LINE);
  doc.roundedRect(x, y, w, h, 6, 6, "FD");

  const coords = trip.route.geometry.coordinates; // [lon, lat]
  if (coords.length < 2) return;
  let minLon = Infinity,
    maxLon = -Infinity,
    minLat = Infinity,
    maxLat = -Infinity;
  for (const [lon, lat] of coords) {
    minLon = Math.min(minLon, lon);
    maxLon = Math.max(maxLon, lon);
    minLat = Math.min(minLat, lat);
    maxLat = Math.max(maxLat, lat);
  }
  const pad = 16;
  const bw = w - pad * 2;
  const bh = h - pad * 2;
  const spanLon = maxLon - minLon || 1;
  const spanLat = maxLat - minLat || 1;
  const scale = Math.min(bw / spanLon, bh / spanLat);
  const offX = x + pad + (bw - spanLon * scale) / 2;
  const offY = y + pad + (bh - spanLat * scale) / 2;
  const px = (lon: number) => offX + (lon - minLon) * scale;
  const py = (lat: number) => offY + (maxLat - lat) * scale; // invert lat

  // route polyline (sample to keep it light)
  doc.setDrawColor(ACCENT);
  doc.setLineWidth(1.6);
  const step = Math.max(1, Math.floor(coords.length / 400));
  let prev: [number, number] | null = null;
  for (let i = 0; i < coords.length; i += step) {
    const [lon, lat] = coords[i];
    const cx = px(lon);
    const cy = py(lat);
    if (prev) doc.line(prev[0], prev[1], cx, cy);
    prev = [cx, cy];
  }

  // stop dots along the route (by mileage proportion)
  const dist = trip.route.distance_miles || 1;
  for (const stop of trip.hos.stops) {
    const t = Math.min(1, Math.max(0, stop.miles_from_start / dist));
    const idx = Math.min(coords.length - 1, Math.round(t * (coords.length - 1)));
    const [lon, lat] = coords[idx];
    doc.setFillColor(STOP_COLOR[stop.kind] ?? MUTED);
    doc.setDrawColor("#ffffff");
    doc.setLineWidth(0.8);
    doc.circle(px(lon), py(lat), 2.6, "FD");
  }
}

/** Draw the FMCSA 24-hour duty grid for one day. */
function drawGrid(doc: jsPDF, log: DailyLog, x: number, y: number, w: number, h: number) {
  const padL = 58;
  const padR = 44;
  const padT = 16;
  const padB = 10;
  const gx = x + padL;
  const gy = y + padT;
  const gw = w - padL - padR;
  const gh = h - padT - padB;
  const rowH = gh / 4;
  const hourW = gw / 24;

  // hour labels
  const labels = [
    "M",
    ...Array.from({ length: 11 }, (_, i) => String(i + 1)),
    "N",
    ...Array.from({ length: 11 }, (_, i) => String(i + 1)),
    "M",
  ];
  doc.setFont("courier", "normal");
  doc.setFontSize(6);
  doc.setTextColor(MUTED);
  for (let hh = 0; hh <= 24; hh++) {
    doc.text(labels[hh], gx + hh * hourW, gy - 5, { align: "center" });
  }

  // grid lines
  doc.setDrawColor(LINE);
  doc.setLineWidth(0.5);
  for (let r = 0; r <= 4; r++) doc.line(gx, gy + r * rowH, gx + gw, gy + r * rowH);
  for (let hh = 0; hh <= 24; hh++) {
    doc.setDrawColor(hh % 6 === 0 ? "#d6d1c8" : LINE);
    doc.line(gx + hh * hourW, gy, gx + hh * hourW, gy + gh);
  }
  // 15-min ticks
  doc.setDrawColor(FAINT);
  doc.setLineWidth(0.3);
  for (let hh = 0; hh < 24; hh++) {
    for (let q = 1; q < 4; q++) {
      const tx = gx + (hh + q / 4) * hourW;
      for (let r = 0; r < 4; r++) {
        const cy = gy + r * rowH + rowH / 2;
        doc.line(tx, cy - 2, tx, cy + 2);
      }
    }
  }

  // row labels + totals
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(INK);
  rowOrder.forEach((s, i) => {
    const cy = gy + i * rowH + rowH / 2 + 2;
    doc.text(`${i + 1}. ${rowLabels[s]}`, gx - 6, cy, { align: "right" });
    doc.setFont("courier", "bold");
    doc.text(`${log.totals[s].toFixed(1)}h`, gx + gw + 6, cy);
    doc.setFont("helvetica", "normal");
  });

  // duty step line
  doc.setLineWidth(1.6);
  rowOrder.forEach((status, i) => {
    doc.setDrawColor(DUTY[status]);
    const cy = gy + i * rowH + rowH / 2;
    log.rows[status].forEach((seg) => {
      doc.line(gx + seg.start_h * hourW, cy, gx + seg.end_h * hourW, cy);
    });
  });
  // vertical connectors at status changes
  const events: { h: number; status: DutyStatus }[] = [];
  rowOrder.forEach((status) => {
    log.rows[status].forEach((seg) => {
      events.push({ h: seg.start_h, status });
      events.push({ h: seg.end_h, status });
    });
  });
  events.sort((a, b) => a.h - b.h);
  doc.setDrawColor(INK);
  doc.setLineWidth(0.6);
  for (let k = 0; k < events.length - 1; k++) {
    const cur = events[k];
    const next = events[k + 1];
    if (Math.abs(cur.h - next.h) < 0.01 && cur.status !== next.status) {
      const cx = gx + cur.h * hourW;
      const y1 = gy + rowOrder.indexOf(cur.status) * rowH + rowH / 2;
      const y2 = gy + rowOrder.indexOf(next.status) * rowH + rowH / 2;
      doc.line(cx, y1, cx, y2);
    }
  }
}

/**
 * Build and download the full trip report as a multi-page PDF:
 * a cover (inputs, summary, route sketch, stops) then one page per log day.
 */
export function downloadTripPdf(trip: TripPlan) {
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const days = trip.daily_logs;
  const totalPages = 1 + days.length;
  // Helvetica (jsPDF's core font) lacks the Unicode arrow glyph, so use a
  // plain, always-renderable separator for the on-page label.
  const routeLabel = `${trip.inputs.pickup_location}  –  ${trip.inputs.dropoff_location}`;

  // ---------- Cover page ----------
  chrome(doc, "Trip report", 1, totalPages);
  let y = M + 52;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(INK);
  doc.text("Trip report", M, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(MUTED);
  y += 18;
  doc.text(routeLabel, M, y);

  // Summary stat row
  y += 26;
  const s = trip.hos.summary;
  const stats = [
    { k: "Distance", v: `${Math.round(s.total_distance_miles).toLocaleString()} mi` },
    { k: "Driving", v: `${s.total_driving_hours.toFixed(1)} h` },
    { k: "On duty", v: `${s.total_on_duty_hours.toFixed(1)} h` },
    { k: "Log days", v: `${s.total_days}` },
  ];
  const cellW = CONTENT_W / 4;
  doc.setDrawColor(LINE);
  doc.setFillColor("#ffffff");
  doc.roundedRect(M, y, CONTENT_W, 46, 5, 5, "FD");
  stats.forEach((st, i) => {
    const cx = M + i * cellW + 12;
    if (i > 0) doc.line(M + i * cellW, y, M + i * cellW, y + 46);
    eyebrow(doc, st.k, cx, y + 16);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);
    doc.setTextColor(INK);
    doc.text(st.v, cx, y + 34);
  });
  y += 46 + 24;

  // Route sketch + inputs side by side
  eyebrow(doc, "Route", M, y);
  y += 8;
  const sketchW = CONTENT_W * 0.62;
  const sketchH = 150;
  drawRouteSketch(doc, trip, M, y, sketchW, sketchH);

  // Inputs card
  const ix = M + sketchW + 14;
  const iw = CONTENT_W - sketchW - 14;
  doc.setFillColor("#ffffff");
  doc.setDrawColor(LINE);
  doc.roundedRect(ix, y, iw, sketchH, 6, 6, "FD");
  const inputs: [string, string][] = [
    ["Current", trip.inputs.current_location],
    ["Pickup", trip.inputs.pickup_location],
    ["Drop-off", trip.inputs.dropoff_location],
    ["Cycle used", `${trip.inputs.current_cycle_used} h`],
  ];
  let iy = y + 20;
  inputs.forEach(([k, v]) => {
    eyebrow(doc, k, ix + 12, iy);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(INK);
    const lines = doc.splitTextToSize(v, iw - 24) as string[];
    doc.text(lines[0], ix + 12, iy + 12);
    iy += 32;
  });
  y += sketchH + 24;

  // Stops table
  eyebrow(doc, `Stops & rests (${trip.hos.stops.length})`, M, y);
  y += 12;
  doc.setDrawColor(LINE);
  doc.setLineWidth(0.6);
  doc.line(M, y, PAGE_W - M, y);
  y += 4;
  trip.hos.stops.forEach((stop) => {
    y += 16;
    doc.setFillColor(STOP_COLOR[stop.kind] ?? MUTED);
    doc.circle(M + 4, y - 3, 3, "F");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(INK);
    doc.text(stop.label, M + 14, y);
    doc.setTextColor(MUTED);
    doc.setFont("courier", "normal");
    doc.setFontSize(8);
    const when = new Date(stop.at).toLocaleString("en-US", {
      month: "short",
      day: "numeric",
      hour: "numeric",
      minute: "2-digit",
    });
    doc.text(when, M + 250, y);
    doc.text(`${Math.round(stop.miles_from_start)} mi`, PAGE_W - M, y, { align: "right" });
  });

  // ---------- One page per log ----------
  days.forEach((log, di) => {
    doc.addPage();
    chrome(doc, `Daily log ${di + 1} of ${days.length}`, di + 2, totalPages);
    let ly = M + 52;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(15);
    doc.setTextColor(INK);
    doc.text(`Driver's Daily Log — Day ${di + 1}`, M, ly);
    doc.setFont("courier", "normal");
    doc.setFontSize(9);
    doc.setTextColor(MUTED);
    ly += 16;
    doc.text(fmtDate(log.date), M, ly);

    // Header metadata (FMCSA §395.8 fields)
    ly += 18;
    const mph =
      trip.route.duration_hours > 0 ? trip.route.distance_miles / trip.route.duration_hours : 55;
    const milesToday = Math.round(log.totals.driving * mph);
    const meta: [string, string][] = [
      ["Total miles today", `${milesToday.toLocaleString()}`],
      ["Carrier", "Spotter Logistics LLC"],
      ["Main office", "Chicago, IL"],
      ["Vehicle", "TRK-1187 / TRL-4402"],
      ["From", trip.inputs.pickup_location],
      ["To", trip.inputs.dropoff_location],
      ["Shipping doc", "BOL-77043 · General freight"],
      ["Driver", "M. Baig"],
    ];
    doc.setDrawColor(LINE);
    doc.roundedRect(M, ly, CONTENT_W, 56, 5, 5, "S");
    const colW = CONTENT_W / 4;
    meta.forEach(([k, v], i) => {
      const col = i % 4;
      const row = Math.floor(i / 4);
      const cx = M + col * colW + 10;
      const cy = ly + 18 + row * 26;
      eyebrow(doc, k, cx, cy);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(INK);
      const line = (doc.splitTextToSize(v, colW - 16) as string[])[0];
      doc.text(line, cx, cy + 11);
    });
    ly += 56 + 20;

    // Grid
    drawGrid(doc, log, M, ly, CONTENT_W, 150);
    ly += 150 + 6;

    // Totals legend
    doc.setFontSize(8);
    let lx = M;
    rowOrder.forEach((st) => {
      doc.setFillColor(DUTY[st]);
      doc.circle(lx + 3, ly, 2.5, "F");
      doc.setFont("helvetica", "normal");
      doc.setTextColor(MUTED);
      doc.text(rowLabels[st], lx + 9, ly + 3);
      doc.setFont("courier", "bold");
      doc.setTextColor(INK);
      const t = `${log.totals[st].toFixed(1)}h`;
      doc.text(t, lx + 9 + doc.getTextWidth(rowLabels[st]) + 6, ly + 3);
      lx += 130;
    });
    ly += 22;

    // Remarks
    eyebrow(doc, "Remarks", M, ly);
    ly += 6;
    doc.setDrawColor(LINE);
    doc.line(M, ly, PAGE_W - M, ly);
    log.remarks.forEach((r) => {
      ly += 14;
      doc.setFont("courier", "normal");
      doc.setFontSize(8);
      doc.setTextColor(MUTED);
      doc.text(fmtHour(r.at_h), M, ly);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(INK);
      const txt = r.location ? `${r.remark} — ${r.location}` : r.remark;
      doc.text(txt, M + 64, ly);
    });
  });

  const safe = routeLabel.replace(/[^a-z0-9]+/gi, "-").toLowerCase();
  doc.save(`spotter-trip-report-${safe}.pdf`);
}
